# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript


trigger:
- master

pool: 'poolwithprivateagent'

stages:
- template: FrontendDeploymentStage.yml  # Build and deploy to dev environment
  parameters:
    ENVIRONMENT: dev
    TargetAppService: 'AppServiceNameGoesHere'
# - template: FrontendDeploymentStage.yml  # Build and deploy to prod environment
#   parameters:
#     ENVIRONMENT: prod